--
-- Account
--

CREATE TABLE IF NOT EXISTS account (
   account_number BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   name TEXT NOT NULL,
   balance INT NOT NULL DEFAULT 0
);

--
-- END
--
