--
-- Account
--

CREATE TABLE IF NOT EXISTS audit (
     id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     created     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
--    TODO should be a foreign key?
     account_number BIGINT NOT NULL,
     amount INT NOT NULL,
     operation TEXT NOT NULL,
     description TEXT NOT NULL
);

--
-- END
--
